// @ts-check
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	// Base is '/ew_wiki/'; all content lives under docs/ewp/, so real routes
	// land at '/ew_wiki/ewp/...' — the nested-URL decision from ticket 01
	// (ew-wiki-real-build), leaving room for a future second mod component
	// as a sibling top-level folder/sidebar group.
	base: '/ew_wiki/',
	// astro dev's on-demand esbuild transform doesn't apply CJS->ESM interop
	// to path-browserify (a CommonJS dep monaco-yaml's yaml.worker imports)
	// before the worker requests it, so the raw CJS file gets served as-is and
	// throws "module is not defined" inside the module worker. `astro build`
	// doesn't have this problem (Rollup's commonjs plugin handles it), so this
	// alias only matters for `astro dev`. See src/playground/path-browserify-esm.js
	// for the shim.
	vite: {
		resolve: {
			alias: {
				'path-browserify': fileURLToPath(new URL('./src/playground/path-browserify-esm.js', import.meta.url)),
			},
		},
	},
	integrations: [
		starlight({
			title: 'Expand World Wiki',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/withastro/starlight' }],
			customCss: ['./src/styles/theme.css'],
			components: {
				// Renders the `complexity` frontmatter badge under the H1 instead
				// of it floating as a first paragraph in the page body.
				PageTitle: './src/components/PageTitle.astro',
			},
			// Everything nests one level under 'EWP' so a future second mod
			// component is a sibling top-level group, not a rebuild of this one.
			sidebar: [
				{ label: 'Home', slug: 'index' },
				{
					label: 'Guide - EWP',
					items: [
						// No dedicated EWP landing page — its old "first script" example
						// duplicated Concepts/script.mdx's "What goes inside a script"
						// (see ticket 04 round 3). Preparation is the entry point instead.
						{ label: 'Preparation', slug: 'ewp/preparation' },
						// Grouped by complexity tier, not by content type (Concepts vs.
						// Examples) — Poke (Intermediate) landing in the same flat,
						// autogenerated Concepts list as Fields/Data/Script (all
						// Beginner) gave a reader no visual warning of the level jump.
						// Prototyped 3 alternatives live against this exact page
						// (see the sidebar-IA note on ticket 09) before picking this one.
						// Bare slug strings (not {label, slug} objects) pull each page's
						// own frontmatter title, so a title edit can't drift from its
						// sidebar label. Sub-tier folders (Concepts/Examples) are gone;
						// the `complexity` badge already on every page carries that
						// distinction now, not the folder it physically lives in.
						{
							label: 'Beginner',
							items: [
								'ewp/concepts/fields',
								'ewp/concepts/data',
								'ewp/concepts/script',
								'ewp/concepts/triggers',
								'ewp/concepts/filter',
								'ewp/examples/first-script',
								'ewp/examples/adding-randomness',
							],
						},
						{
							label: 'Intermediate',
							items: [
								'ewp/concepts/spawn-vs-swap',
								'ewp/concepts/objects-filtering',
								'ewp/concepts/poke',
								'ewp/concepts/pars',
								'ewp/concepts/functions',
								'ewp/concepts/custom-data',
								'ewp/concepts/rpcs',
								// Type: Time / Type: Realtime land here as each is ported
								// (ticket 07) — not listed yet since a sidebar entry needs
								// a real page to link to.
							],
						},
						// Reference/Troubleshooting removed for now (2026-09-07) — placeholder
						// scaffolding from early tickets, not real content. Re-add when a section
						// actually has something to say (Reference needs schema-gen tooling that
						// doesn't exist yet; Troubleshooting needs the validator's diagnosis text).
					],
				},
				// { label: 'A Second Mod', items: [{ autogenerate: { directory: 'second-mod' } }] },
			],
		}),
	],
});
