// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	// Base is '/ew_wiki/'; all content lives under docs/ewp/, so real routes
	// land at '/ew_wiki/ewp/...' — the nested-URL decision from ticket 01
	// (ew-wiki-real-build), leaving room for a future second mod component
	// as a sibling top-level folder/sidebar group.
	base: '/ew_wiki/',
	integrations: [
		starlight({
			title: 'Expand World Wiki',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/withastro/starlight' }],
			customCss: ['./src/styles/theme.css'],
			components: {
				// Renders the `complexity` frontmatter badge under the H1 instead
				// of it floating as a first paragraph in the page body.
				PageTitle: './src/components/PageTitle.astro',
			},
			// Everything nests one level under 'EWP' so a future second mod
			// component is a sibling top-level group, not a rebuild of this one.
			sidebar: [
				{ label: 'Home', slug: 'index' },
				{
					label: 'Guide - EWP',
					items: [
						// No dedicated EWP landing page — its old "first script" example
						// duplicated Concepts/script.mdx's "What goes inside a script"
						// (see ticket 04 round 3). Preparation is the entry point instead.
						{ label: 'Preparation', slug: 'ewp/preparation' },
						// Grouped by complexity tier, not by content type (Concepts vs.
						// Examples) — Poke (Intermediate) landing in the same flat,
						// autogenerated Concepts list as Fields/Data/Script (all
						// Beginner) gave a reader no visual warning of the level jump.
						// Prototyped 3 alternatives live against this exact page
						// (see the sidebar-IA note on ticket 09) before picking this one.
						// Bare slug strings (not {label, slug} objects) pull each page's
						// own frontmatter title, so a title edit can't drift from its
						// sidebar label. Sub-tier folders (Concepts/Examples) are gone;
						// the `complexity` badge already on every page carries that
						// distinction now, not the folder it physically lives in.
						{
							label: 'Beginner',
							items: [
								'ewp/concepts/basic-fields',
								'ewp/concepts/basic-data',
								'ewp/concepts/start-scripting',
								'ewp/concepts/basic-triggers',
								'ewp/concepts/basic-filter',
								'ewp/examples/first-script',
								'ewp/examples/basic-rng',
							],
						},
						{
							label: 'Intermediate',
							items: [
								'ewp/concepts/spawn-vs-swap',
								'ewp/concepts/objects-filtering',
								'ewp/concepts/basic-poke',
								'ewp/concepts/basic-pars',
								'ewp/concepts/basic-functions',
								'ewp/concepts/custom-data',
								'ewp/concepts/basic-rpcs',
							],
						},
						// Advanced: each page teaches genuinely new fields/functions/trigger
						// types not covered anywhere else in the guide — skipping one leaves
						// a real gap. type: time / type: realtime land here, not Intermediate
						// (supersedes the plan noted above — confirmed with the maintainer
						// 2026-09-08).
						// Order echoes the Beginner/Intermediate sequence — each Advanced page
						// sits roughly where its basic/intermediate counterpart does (triggers,
						// then filter/objects, then poke, then functions, then custom-data, then
						// rpcs last, matching rpcs sitting last in Intermediate) — confirmed with
						// the maintainer 2026-09-10. advanced-filter-condition is the one
						// exception: forced to the very end regardless of that ranking, since
						// condition: is EWP's newest and most advanced feature.
						{
							label: 'Advanced',
							items: [
								'ewp/concepts/advanced-triggers-change',
								'ewp/concepts/advanced-triggers-time',
								'ewp/concepts/advanced-triggers-realtime',
								'ewp/concepts/advanced-triggers-no-prefab',
								'ewp/concepts/advanced-filter-plural',
								'ewp/concepts/advanced-poke-mechanics',
								'ewp/concepts/advanced-poke-creative-systems',
								'ewp/concepts/advanced-functions',
								'ewp/concepts/ewp-key',
								'ewp/concepts/advanced-rpcs',
								'ewp/concepts/advanced-filter-condition',
							],
						},
						// Extended Reading: full, proven real-world scripts built entirely
						// from fields/functions already taught above — nothing here is
						// required to learn EWP fully. For a reader who wants complete
						// worked systems, not new syntax.
						{
							label: 'Extended Reading',
							items: [
								'ewp/examples/bee-ecosystem',
								'ewp/examples/custom-ship-data',
								'ewp/examples/world-progression',
								'ewp/examples/auto-upgrade-station',
								'ewp/examples/village-cargo',
							],
						},
						// Reference/Troubleshooting removed for now (2026-09-07) — placeholder
						// scaffolding from early tickets, not real content. Re-add when a section
						// actually has something to say (Reference needs schema-gen tooling that
						// doesn't exist yet; Troubleshooting needs the validator's diagnosis text).
					],
				},
				// { label: 'A Second Mod', items: [{ autogenerate: { directory: 'second-mod' } }] },
			],
		}),
	],
});
